// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelfRef.reset));
    bufp->chgBit(oldp+1,(vlSelfRef.clk));
    bufp->chgBit(oldp+2,(vlSelfRef.is_halted));
    bufp->chgIData(oldp+3,(vlSelfRef.print_reg[0]),32);
    bufp->chgIData(oldp+4,(vlSelfRef.print_reg[1]),32);
    bufp->chgIData(oldp+5,(vlSelfRef.print_reg[2]),32);
    bufp->chgIData(oldp+6,(vlSelfRef.print_reg[3]),32);
    bufp->chgIData(oldp+7,(vlSelfRef.print_reg[4]),32);
    bufp->chgIData(oldp+8,(vlSelfRef.print_reg[5]),32);
    bufp->chgIData(oldp+9,(vlSelfRef.print_reg[6]),32);
    bufp->chgIData(oldp+10,(vlSelfRef.print_reg[7]),32);
    bufp->chgIData(oldp+11,(vlSelfRef.print_reg[8]),32);
    bufp->chgIData(oldp+12,(vlSelfRef.print_reg[9]),32);
    bufp->chgIData(oldp+13,(vlSelfRef.print_reg[10]),32);
    bufp->chgIData(oldp+14,(vlSelfRef.print_reg[11]),32);
    bufp->chgIData(oldp+15,(vlSelfRef.print_reg[12]),32);
    bufp->chgIData(oldp+16,(vlSelfRef.print_reg[13]),32);
    bufp->chgIData(oldp+17,(vlSelfRef.print_reg[14]),32);
    bufp->chgIData(oldp+18,(vlSelfRef.print_reg[15]),32);
    bufp->chgIData(oldp+19,(vlSelfRef.print_reg[16]),32);
    bufp->chgIData(oldp+20,(vlSelfRef.print_reg[17]),32);
    bufp->chgIData(oldp+21,(vlSelfRef.print_reg[18]),32);
    bufp->chgIData(oldp+22,(vlSelfRef.print_reg[19]),32);
    bufp->chgIData(oldp+23,(vlSelfRef.print_reg[20]),32);
    bufp->chgIData(oldp+24,(vlSelfRef.print_reg[21]),32);
    bufp->chgIData(oldp+25,(vlSelfRef.print_reg[22]),32);
    bufp->chgIData(oldp+26,(vlSelfRef.print_reg[23]),32);
    bufp->chgIData(oldp+27,(vlSelfRef.print_reg[24]),32);
    bufp->chgIData(oldp+28,(vlSelfRef.print_reg[25]),32);
    bufp->chgIData(oldp+29,(vlSelfRef.print_reg[26]),32);
    bufp->chgIData(oldp+30,(vlSelfRef.print_reg[27]),32);
    bufp->chgIData(oldp+31,(vlSelfRef.print_reg[28]),32);
    bufp->chgIData(oldp+32,(vlSelfRef.print_reg[29]),32);
    bufp->chgIData(oldp+33,(vlSelfRef.print_reg[30]),32);
    bufp->chgIData(oldp+34,(vlSelfRef.print_reg[31]),32);
    bufp->chgBit(oldp+35,(vlSelfRef.top__DOT__reset));
    bufp->chgBit(oldp+36,(vlSelfRef.top__DOT__clk));
    bufp->chgBit(oldp+37,(vlSelfRef.top__DOT__is_halted));
    bufp->chgIData(oldp+38,(vlSelfRef.top__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+39,(vlSelfRef.top__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+40,(vlSelfRef.top__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+41,(vlSelfRef.top__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+42,(vlSelfRef.top__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+43,(vlSelfRef.top__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+44,(vlSelfRef.top__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+45,(vlSelfRef.top__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+46,(vlSelfRef.top__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+47,(vlSelfRef.top__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+48,(vlSelfRef.top__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+49,(vlSelfRef.top__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+50,(vlSelfRef.top__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+51,(vlSelfRef.top__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+52,(vlSelfRef.top__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+53,(vlSelfRef.top__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+54,(vlSelfRef.top__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+55,(vlSelfRef.top__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+56,(vlSelfRef.top__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+57,(vlSelfRef.top__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+58,(vlSelfRef.top__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+59,(vlSelfRef.top__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+60,(vlSelfRef.top__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+61,(vlSelfRef.top__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+62,(vlSelfRef.top__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+63,(vlSelfRef.top__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+64,(vlSelfRef.top__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+65,(vlSelfRef.top__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+66,(vlSelfRef.top__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+67,(vlSelfRef.top__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+68,(vlSelfRef.top__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+69,(vlSelfRef.top__DOT__print_reg[31]),32);
    bufp->chgBit(oldp+70,(vlSelfRef.top__DOT__cpu__DOT__reset));
    bufp->chgBit(oldp+71,(vlSelfRef.top__DOT__cpu__DOT__clk));
    bufp->chgBit(oldp+72,(vlSelfRef.top__DOT__cpu__DOT__is_halted));
    bufp->chgIData(oldp+73,(vlSelfRef.top__DOT__cpu__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+74,(vlSelfRef.top__DOT__cpu__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+75,(vlSelfRef.top__DOT__cpu__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+76,(vlSelfRef.top__DOT__cpu__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+77,(vlSelfRef.top__DOT__cpu__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+78,(vlSelfRef.top__DOT__cpu__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+79,(vlSelfRef.top__DOT__cpu__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+80,(vlSelfRef.top__DOT__cpu__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+81,(vlSelfRef.top__DOT__cpu__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+82,(vlSelfRef.top__DOT__cpu__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+83,(vlSelfRef.top__DOT__cpu__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+84,(vlSelfRef.top__DOT__cpu__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+85,(vlSelfRef.top__DOT__cpu__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+86,(vlSelfRef.top__DOT__cpu__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+87,(vlSelfRef.top__DOT__cpu__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+88,(vlSelfRef.top__DOT__cpu__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+89,(vlSelfRef.top__DOT__cpu__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+90,(vlSelfRef.top__DOT__cpu__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+91,(vlSelfRef.top__DOT__cpu__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+92,(vlSelfRef.top__DOT__cpu__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+93,(vlSelfRef.top__DOT__cpu__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+94,(vlSelfRef.top__DOT__cpu__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+95,(vlSelfRef.top__DOT__cpu__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+96,(vlSelfRef.top__DOT__cpu__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+97,(vlSelfRef.top__DOT__cpu__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+98,(vlSelfRef.top__DOT__cpu__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+99,(vlSelfRef.top__DOT__cpu__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+100,(vlSelfRef.top__DOT__cpu__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+101,(vlSelfRef.top__DOT__cpu__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+102,(vlSelfRef.top__DOT__cpu__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+103,(vlSelfRef.top__DOT__cpu__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+104,(vlSelfRef.top__DOT__cpu__DOT__print_reg[31]),32);
    bufp->chgBit(oldp+105,(vlSelfRef.top__DOT__cpu__DOT__pc_write));
    bufp->chgBit(oldp+106,(vlSelfRef.top__DOT__cpu__DOT__is_ecall));
    bufp->chgCData(oldp+107,(vlSelfRef.top__DOT__cpu__DOT__forwardA),2);
    bufp->chgCData(oldp+108,(vlSelfRef.top__DOT__cpu__DOT__forwardB),2);
    bufp->chgIData(oldp+109,(vlSelfRef.top__DOT__cpu__DOT__current_pc),32);
    bufp->chgIData(oldp+110,(vlSelfRef.top__DOT__cpu__DOT__imm_gen_out),32);
    bufp->chgIData(oldp+111,(vlSelfRef.top__DOT__cpu__DOT__alu_out),32);
    bufp->chgIData(oldp+112,(vlSelfRef.top__DOT__cpu__DOT__mem_dout),32);
    bufp->chgIData(oldp+113,(vlSelfRef.top__DOT__cpu__DOT__rs1_dout),32);
    bufp->chgIData(oldp+114,(vlSelfRef.top__DOT__cpu__DOT__rs2_dout),32);
    bufp->chgBit(oldp+115,(vlSelfRef.top__DOT__cpu__DOT__gshare_predict_taken));
    bufp->chgBit(oldp+116,(vlSelfRef.top__DOT__cpu__DOT__actual_taken));
    bufp->chgBit(oldp+117,(vlSelfRef.top__DOT__cpu__DOT__branch_mispredicted));
    bufp->chgBit(oldp+118,(vlSelfRef.top__DOT__cpu__DOT__gshare_enable));
    bufp->chgIData(oldp+119,(vlSelfRef.top__DOT__cpu__DOT__gshare_next_pc),32);
    bufp->chgIData(oldp+120,(vlSelfRef.top__DOT__cpu__DOT__correct_pc),32);
    bufp->chgBit(oldp+121,(vlSelfRef.top__DOT__cpu__DOT__is_ready));
    bufp->chgBit(oldp+122,(vlSelfRef.top__DOT__cpu__DOT__is_output_valid));
    bufp->chgBit(oldp+123,(vlSelfRef.top__DOT__cpu__DOT__is_hit));
    bufp->chgBit(oldp+124,(vlSelfRef.top__DOT__cpu__DOT__cache_busy));
    bufp->chgIData(oldp+125,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_inst),32);
    bufp->chgBit(oldp+126,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_write));
    bufp->chgIData(oldp+127,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_pc),32);
    bufp->chgBit(oldp+128,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_sel));
    bufp->chgCData(oldp+129,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_alu_op),4);
    bufp->chgBit(oldp+130,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_alu_src));
    bufp->chgBit(oldp+131,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_write));
    bufp->chgBit(oldp+132,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_read));
    bufp->chgBit(oldp+133,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_to_reg));
    bufp->chgBit(oldp+134,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_reg_write));
    bufp->chgBit(oldp+135,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_pc_to_reg));
    bufp->chgIData(oldp+136,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_pc),32);
    bufp->chgBit(oldp+137,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_jalr));
    bufp->chgBit(oldp+138,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_jal));
    bufp->chgBit(oldp+139,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_branch));
    bufp->chgBit(oldp+140,(vlSelfRef.top__DOT__cpu__DOT__alu_bcond));
    bufp->chgIData(oldp+141,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs1_data),32);
    bufp->chgIData(oldp+142,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs2_data),32);
    bufp->chgIData(oldp+143,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_imm),32);
    bufp->chgCData(oldp+144,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rd),5);
    bufp->chgCData(oldp+145,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs1),5);
    bufp->chgCData(oldp+146,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs2),5);
    bufp->chgBit(oldp+147,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_write));
    bufp->chgBit(oldp+148,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_read));
    bufp->chgBit(oldp+149,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_to_reg));
    bufp->chgBit(oldp+150,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_reg_write));
    bufp->chgBit(oldp+151,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_pc_to_reg));
    bufp->chgIData(oldp+152,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_pc),32);
    bufp->chgIData(oldp+153,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_alu_out),32);
    bufp->chgIData(oldp+154,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_dmem_data),32);
    bufp->chgCData(oldp+155,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_rd),5);
    bufp->chgBit(oldp+156,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg));
    bufp->chgBit(oldp+157,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_reg_write));
    bufp->chgBit(oldp+158,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_pc_to_reg));
    bufp->chgIData(oldp+159,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_pc),32);
    bufp->chgCData(oldp+160,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_rd),5);
    bufp->chgIData(oldp+161,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1),32);
    bufp->chgIData(oldp+162,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_2),32);
    bufp->chgIData(oldp+163,(vlSelfRef.top__DOT__cpu__DOT__alu_in_1),32);
    bufp->chgIData(oldp+164,(vlSelfRef.top__DOT__cpu__DOT__alu_in_2_pre),32);
    bufp->chgIData(oldp+165,(vlSelfRef.top__DOT__cpu__DOT__alu_in_2),32);
    bufp->chgIData(oldp+166,(vlSelfRef.top__DOT__cpu__DOT__wb_data),32);
    bufp->chgIData(oldp+167,(vlSelfRef.top__DOT__cpu__DOT__inst),32);
    bufp->chgBit(oldp+168,(vlSelfRef.top__DOT__cpu__DOT__mem_read));
    bufp->chgBit(oldp+169,(vlSelfRef.top__DOT__cpu__DOT__mem_to_reg));
    bufp->chgBit(oldp+170,(vlSelfRef.top__DOT__cpu__DOT__mem_write));
    bufp->chgBit(oldp+171,(vlSelfRef.top__DOT__cpu__DOT__reg_write));
    bufp->chgBit(oldp+172,(vlSelfRef.top__DOT__cpu__DOT__alu_src));
    bufp->chgBit(oldp+173,(vlSelfRef.top__DOT__cpu__DOT__pc_to_reg));
    bufp->chgCData(oldp+174,(vlSelfRef.top__DOT__cpu__DOT__alu_op),4);
    bufp->chgBit(oldp+175,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_halt));
    bufp->chgBit(oldp+176,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_halt));
    bufp->chgBit(oldp+177,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_halt));
    bufp->chgBit(oldp+178,(vlSelfRef.top__DOT__cpu__DOT__final_halt));
    bufp->chgIData(oldp+179,(vlSelfRef.top__DOT__cpu__DOT__jalr_pc),32);
    bufp->chgIData(oldp+180,(vlSelfRef.top__DOT__cpu__DOT__jal_pc),32);
    bufp->chgIData(oldp+181,(vlSelfRef.top__DOT__cpu__DOT__next_pc),32);
    bufp->chgBit(oldp+182,(vlSelfRef.top__DOT__cpu__DOT__is_jal));
    bufp->chgBit(oldp+183,(vlSelfRef.top__DOT__cpu__DOT__is_jalr));
    bufp->chgBit(oldp+184,(vlSelfRef.top__DOT__cpu__DOT__is_branch));
    bufp->chgBit(oldp+185,(vlSelfRef.top__DOT__cpu__DOT__is_input_valid));
    bufp->chgCData(oldp+186,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_op),4);
    bufp->chgIData(oldp+187,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_in_1),32);
    bufp->chgIData(oldp+188,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_in_2),32);
    bufp->chgIData(oldp+189,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_result),32);
    bufp->chgBit(oldp+190,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_bcond));
    bufp->chgCData(oldp+191,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__shamt),5);
    bufp->chgBit(oldp+192,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__reset));
    bufp->chgBit(oldp+193,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__clk));
    bufp->chgBit(oldp+194,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_input_valid));
    bufp->chgIData(oldp+195,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__addr),32);
    bufp->chgBit(oldp+196,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_read));
    bufp->chgBit(oldp+197,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_write));
    bufp->chgIData(oldp+198,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__din),32);
    bufp->chgBit(oldp+199,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_ready));
    bufp->chgBit(oldp+200,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_output_valid));
    bufp->chgIData(oldp+201,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dout),32);
    bufp->chgBit(oldp+202,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_hit));
    bufp->chgIData(oldp+203,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__total_count),32);
    bufp->chgIData(oldp+204,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__hit_count),32);
    bufp->chgIData(oldp+205,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__miss_count),32);
    bufp->chgBit(oldp+206,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__hit_event));
    bufp->chgBit(oldp+207,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__miss_event));
    bufp->chgIData(oldp+208,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag),26);
    bufp->chgCData(oldp+209,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__idx),2);
    bufp->chgCData(oldp+210,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__word_offset),2);
    bufp->chgIData(oldp+211,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [0U][0U]),26);
    bufp->chgIData(oldp+212,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [0U][1U]),26);
    bufp->chgIData(oldp+213,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [0U][2U]),26);
    bufp->chgIData(oldp+214,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [0U][3U]),26);
    bufp->chgIData(oldp+215,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [1U][0U]),26);
    bufp->chgIData(oldp+216,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [1U][1U]),26);
    bufp->chgIData(oldp+217,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [1U][2U]),26);
    bufp->chgIData(oldp+218,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [1U][3U]),26);
    bufp->chgIData(oldp+219,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [2U][0U]),26);
    bufp->chgIData(oldp+220,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [2U][1U]),26);
    bufp->chgIData(oldp+221,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [2U][2U]),26);
    bufp->chgIData(oldp+222,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [2U][3U]),26);
    bufp->chgIData(oldp+223,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [3U][0U]),26);
    bufp->chgIData(oldp+224,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [3U][1U]),26);
    bufp->chgIData(oldp+225,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [3U][2U]),26);
    bufp->chgIData(oldp+226,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [3U][3U]),26);
    bufp->chgBit(oldp+227,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [0U][0U]));
    bufp->chgBit(oldp+228,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [0U][1U]));
    bufp->chgBit(oldp+229,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [0U][2U]));
    bufp->chgBit(oldp+230,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [0U][3U]));
    bufp->chgBit(oldp+231,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [1U][0U]));
    bufp->chgBit(oldp+232,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [1U][1U]));
    bufp->chgBit(oldp+233,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [1U][2U]));
    bufp->chgBit(oldp+234,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [1U][3U]));
    bufp->chgBit(oldp+235,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [2U][0U]));
    bufp->chgBit(oldp+236,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [2U][1U]));
    bufp->chgBit(oldp+237,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [2U][2U]));
    bufp->chgBit(oldp+238,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [2U][3U]));
    bufp->chgBit(oldp+239,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [3U][0U]));
    bufp->chgBit(oldp+240,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [3U][1U]));
    bufp->chgBit(oldp+241,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [3U][2U]));
    bufp->chgBit(oldp+242,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid_bank
                           [3U][3U]));
    bufp->chgBit(oldp+243,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [0U][0U]));
    bufp->chgBit(oldp+244,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [0U][1U]));
    bufp->chgBit(oldp+245,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [0U][2U]));
    bufp->chgBit(oldp+246,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [0U][3U]));
    bufp->chgBit(oldp+247,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [1U][0U]));
    bufp->chgBit(oldp+248,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [1U][1U]));
    bufp->chgBit(oldp+249,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [1U][2U]));
    bufp->chgBit(oldp+250,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [1U][3U]));
    bufp->chgBit(oldp+251,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [2U][0U]));
    bufp->chgBit(oldp+252,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [2U][1U]));
    bufp->chgBit(oldp+253,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [2U][2U]));
    bufp->chgBit(oldp+254,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [2U][3U]));
    bufp->chgBit(oldp+255,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [3U][0U]));
    bufp->chgBit(oldp+256,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [3U][1U]));
    bufp->chgBit(oldp+257,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [3U][2U]));
    bufp->chgBit(oldp+258,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty_bank
                           [3U][3U]));
    bufp->chgWData(oldp+259,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [0U][0U]),128);
    bufp->chgWData(oldp+263,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [0U][1U]),128);
    bufp->chgWData(oldp+267,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [0U][2U]),128);
    bufp->chgWData(oldp+271,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [0U][3U]),128);
    bufp->chgWData(oldp+275,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [1U][0U]),128);
    bufp->chgWData(oldp+279,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [1U][1U]),128);
    bufp->chgWData(oldp+283,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [1U][2U]),128);
    bufp->chgWData(oldp+287,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [1U][3U]),128);
    bufp->chgWData(oldp+291,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [2U][0U]),128);
    bufp->chgWData(oldp+295,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [2U][1U]),128);
    bufp->chgWData(oldp+299,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [2U][2U]),128);
    bufp->chgWData(oldp+303,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [2U][3U]),128);
    bufp->chgWData(oldp+307,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [3U][0U]),128);
    bufp->chgWData(oldp+311,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [3U][1U]),128);
    bufp->chgWData(oldp+315,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [3U][2U]),128);
    bufp->chgWData(oldp+319,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [3U][3U]),128);
    bufp->chgBit(oldp+323,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_read_req));
    bufp->chgBit(oldp+324,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_write_req));
    bufp->chgIData(oldp+325,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_addr),32);
    bufp->chgWData(oldp+326,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_rdata),128);
    bufp->chgBit(oldp+330,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_output_valid));
    bufp->chgBit(oldp+331,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_ready));
    bufp->chgCData(oldp+332,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__way_hit),4);
    bufp->chgCData(oldp+333,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__hit_way),2);
    bufp->chgCData(oldp+334,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__replace_way),2);
    bufp->chgWData(oldp+335,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__selected_line),128);
    bufp->chgCData(oldp+339,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__current_state),2);
    bufp->chgCData(oldp+340,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__next_state),2);
    bufp->chgWData(oldp+341,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__cache_in),128);
    bufp->chgBit(oldp+345,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__cache_dirty));
    bufp->chgBit(oldp+346,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__cache_write));
    bufp->chgCData(oldp+347,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__write_way),2);
    bufp->chgIData(oldp+348,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__i),32);
    bufp->chgIData(oldp+349,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__j),32);
    bufp->chgIData(oldp+350,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__k),32);
    bufp->chgBit(oldp+351,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__reset));
    bufp->chgBit(oldp+352,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__clk));
    bufp->chgBit(oldp+353,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_input_valid));
    bufp->chgIData(oldp+354,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__addr),32);
    bufp->chgBit(oldp+355,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_read));
    bufp->chgBit(oldp+356,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_write));
    bufp->chgWData(oldp+357,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__din),128);
    bufp->chgBit(oldp+361,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_output_valid));
    bufp->chgWData(oldp+362,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__dout),128);
    bufp->chgBit(oldp+366,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_ready));
    bufp->chgIData(oldp+367,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__i),32);
    bufp->chgIData(oldp+368,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__delay_counter),32);
    bufp->chgBit(oldp+369,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__request_arrived));
    bufp->chgIData(oldp+370,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__unnamedblk1__DOT__w),32);
    bufp->chgIData(oldp+371,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__unnamedblk2__DOT__i),32);
    bufp->chgIData(oldp+372,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__unnamedblk3__DOT__i),32);
    bufp->chgBit(oldp+373,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__unnamedblk3__DOT__unnamedblk4__DOT__is_lru));
    bufp->chgIData(oldp+374,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__j),32);
    bufp->chgIData(oldp+375,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__unnamedblk6__DOT__i),32);
    bufp->chgCData(oldp+376,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__opcode),7);
    bufp->chgCData(oldp+377,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__funct3),3);
    bufp->chgCData(oldp+378,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__funct7),7);
    bufp->chgBit(oldp+379,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read));
    bufp->chgBit(oldp+380,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_to_reg));
    bufp->chgBit(oldp+381,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write));
    bufp->chgBit(oldp+382,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__reg_write));
    bufp->chgCData(oldp+383,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__alu_op),4);
    bufp->chgBit(oldp+384,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src));
    bufp->chgBit(oldp+385,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_jal));
    bufp->chgBit(oldp+386,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_jalr));
    bufp->chgBit(oldp+387,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_branch));
    bufp->chgBit(oldp+388,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__pc_to_reg));
    bufp->chgBit(oldp+389,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall));
    bufp->chgCData(oldp+390,(vlSelfRef.top__DOT__cpu__DOT__forwarding__DOT__rs1),5);
    bufp->chgCData(oldp+391,(vlSelfRef.top__DOT__cpu__DOT__forwarding__DOT__rs2),5);
    bufp->chgCData(oldp+392,(vlSelfRef.top__DOT__cpu__DOT__forwarding__DOT__EX_MEM_rd),5);
    bufp->chgCData(oldp+393,(vlSelfRef.top__DOT__cpu__DOT__forwarding__DOT__MEM_WB_rd),5);
    bufp->chgBit(oldp+394,(vlSelfRef.top__DOT__cpu__DOT__forwarding__DOT__EX_MEM_reg_write));
    bufp->chgBit(oldp+395,(vlSelfRef.top__DOT__cpu__DOT__forwarding__DOT__MEM_WB_reg_write));
    bufp->chgCData(oldp+396,(vlSelfRef.top__DOT__cpu__DOT__forwarding__DOT__forwardA),2);
    bufp->chgCData(oldp+397,(vlSelfRef.top__DOT__cpu__DOT__forwarding__DOT__forwardB),2);
    bufp->chgBit(oldp+398,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__clk));
    bufp->chgBit(oldp+399,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__reset));
    bufp->chgIData(oldp+400,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__pc),32);
    bufp->chgBit(oldp+401,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__update_valid));
    bufp->chgIData(oldp+402,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__update_pc),32);
    bufp->chgIData(oldp+403,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__update_target),32);
    bufp->chgBit(oldp+404,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__update_taken));
    bufp->chgIData(oldp+405,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__next_pc),32);
    bufp->chgBit(oldp+406,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__predict_taken));
    bufp->chgCData(oldp+407,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__bhsr),7);
    bufp->chgIData(oldp+408,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[0]),32);
    bufp->chgIData(oldp+409,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[1]),32);
    bufp->chgIData(oldp+410,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[2]),32);
    bufp->chgIData(oldp+411,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[3]),32);
    bufp->chgIData(oldp+412,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[4]),32);
    bufp->chgIData(oldp+413,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[5]),32);
    bufp->chgIData(oldp+414,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[6]),32);
    bufp->chgIData(oldp+415,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[7]),32);
    bufp->chgIData(oldp+416,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[8]),32);
    bufp->chgIData(oldp+417,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[9]),32);
    bufp->chgIData(oldp+418,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[10]),32);
    bufp->chgIData(oldp+419,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[11]),32);
    bufp->chgIData(oldp+420,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[12]),32);
    bufp->chgIData(oldp+421,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[13]),32);
    bufp->chgIData(oldp+422,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[14]),32);
    bufp->chgIData(oldp+423,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[15]),32);
    bufp->chgIData(oldp+424,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[16]),32);
    bufp->chgIData(oldp+425,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[17]),32);
    bufp->chgIData(oldp+426,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[18]),32);
    bufp->chgIData(oldp+427,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[19]),32);
    bufp->chgIData(oldp+428,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[20]),32);
    bufp->chgIData(oldp+429,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[21]),32);
    bufp->chgIData(oldp+430,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[22]),32);
    bufp->chgIData(oldp+431,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[23]),32);
    bufp->chgIData(oldp+432,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[24]),32);
    bufp->chgIData(oldp+433,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[25]),32);
    bufp->chgIData(oldp+434,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[26]),32);
    bufp->chgIData(oldp+435,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[27]),32);
    bufp->chgIData(oldp+436,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[28]),32);
    bufp->chgIData(oldp+437,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[29]),32);
    bufp->chgIData(oldp+438,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[30]),32);
    bufp->chgIData(oldp+439,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__btb[31]),32);
    bufp->chgIData(oldp+440,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[0]),25);
    bufp->chgIData(oldp+441,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[1]),25);
    bufp->chgIData(oldp+442,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[2]),25);
    bufp->chgIData(oldp+443,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[3]),25);
    bufp->chgIData(oldp+444,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[4]),25);
    bufp->chgIData(oldp+445,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[5]),25);
    bufp->chgIData(oldp+446,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[6]),25);
    bufp->chgIData(oldp+447,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[7]),25);
    bufp->chgIData(oldp+448,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[8]),25);
    bufp->chgIData(oldp+449,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[9]),25);
    bufp->chgIData(oldp+450,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[10]),25);
    bufp->chgIData(oldp+451,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[11]),25);
    bufp->chgIData(oldp+452,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[12]),25);
    bufp->chgIData(oldp+453,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[13]),25);
    bufp->chgIData(oldp+454,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[14]),25);
    bufp->chgIData(oldp+455,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[15]),25);
    bufp->chgIData(oldp+456,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[16]),25);
    bufp->chgIData(oldp+457,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[17]),25);
    bufp->chgIData(oldp+458,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[18]),25);
    bufp->chgIData(oldp+459,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[19]),25);
    bufp->chgIData(oldp+460,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[20]),25);
    bufp->chgIData(oldp+461,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[21]),25);
    bufp->chgIData(oldp+462,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[22]),25);
    bufp->chgIData(oldp+463,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[23]),25);
    bufp->chgIData(oldp+464,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[24]),25);
    bufp->chgIData(oldp+465,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[25]),25);
    bufp->chgIData(oldp+466,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[26]),25);
    bufp->chgIData(oldp+467,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[27]),25);
    bufp->chgIData(oldp+468,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[28]),25);
    bufp->chgIData(oldp+469,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[29]),25);
    bufp->chgIData(oldp+470,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[30]),25);
    bufp->chgIData(oldp+471,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_table[31]),25);
    bufp->chgCData(oldp+472,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__pc_idx),5);
    bufp->chgIData(oldp+473,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__pc_tag),25);
    bufp->chgCData(oldp+474,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__update_idx),5);
    bufp->chgIData(oldp+475,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__update_tag),25);
    bufp->chgCData(oldp+476,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__pht_idx),7);
    bufp->chgCData(oldp+477,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__update_pht_idx),7);
    bufp->chgBit(oldp+478,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__tag_match));
    bufp->chgBit(oldp+479,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__pht_taken));
    bufp->chgIData(oldp+480,(vlSelfRef.top__DOT__cpu__DOT__gshare__DOT__i),32);
    bufp->chgCData(oldp+481,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__rs1),5);
    bufp->chgCData(oldp+482,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__rs2),5);
    bufp->chgCData(oldp+483,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__opcode),7);
    bufp->chgCData(oldp+484,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__ID_EX_rd),5);
    bufp->chgBit(oldp+485,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__ID_EX_mem_read));
    bufp->chgBit(oldp+486,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__ID_EX_reg_write));
    bufp->chgBit(oldp+487,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__pc_write));
    bufp->chgBit(oldp+488,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__IF_ID_write));
    bufp->chgBit(oldp+489,(vlSelfRef.top__DOT__cpu__DOT__hazard_detector__DOT__ID_EX_sel));
    bufp->chgBit(oldp+490,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__reset));
    bufp->chgBit(oldp+491,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__clk));
    bufp->chgIData(oldp+492,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__addr),32);
    bufp->chgIData(oldp+493,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__dout),32);
    bufp->chgIData(oldp+494,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__i),32);
    bufp->chgIData(oldp+495,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__imem_addr),32);
    bufp->chgIData(oldp+496,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__part_of_inst),32);
    bufp->chgIData(oldp+497,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out),32);
    bufp->chgCData(oldp+498,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__opcode),7);
    bufp->chgBit(oldp+499,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__reset));
    bufp->chgBit(oldp+500,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__clk));
    bufp->chgIData(oldp+501,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__next_pc),32);
    bufp->chgBit(oldp+502,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__pc_write));
    bufp->chgIData(oldp+503,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__current_pc),32);
    bufp->chgBit(oldp+504,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__reset));
    bufp->chgBit(oldp+505,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__clk));
    bufp->chgCData(oldp+506,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1),5);
    bufp->chgCData(oldp+507,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2),5);
    bufp->chgCData(oldp+508,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd),5);
    bufp->chgIData(oldp+509,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd_din),32);
    bufp->chgBit(oldp+510,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__write_enable));
    bufp->chgIData(oldp+511,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1_dout),32);
    bufp->chgIData(oldp+512,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2_dout),32);
    bufp->chgIData(oldp+513,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+514,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+515,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+516,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+517,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+518,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+519,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+520,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+521,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+522,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+523,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+524,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+525,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+526,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+527,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+528,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+529,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+530,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+531,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+532,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+533,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+534,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+535,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+536,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+537,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+538,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+539,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+540,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+541,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+542,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+543,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+544,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[31]),32);
    bufp->chgIData(oldp+545,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__i),32);
    bufp->chgIData(oldp+546,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[0]),32);
    bufp->chgIData(oldp+547,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[1]),32);
    bufp->chgIData(oldp+548,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[2]),32);
    bufp->chgIData(oldp+549,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[3]),32);
    bufp->chgIData(oldp+550,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[4]),32);
    bufp->chgIData(oldp+551,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[5]),32);
    bufp->chgIData(oldp+552,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[6]),32);
    bufp->chgIData(oldp+553,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[7]),32);
    bufp->chgIData(oldp+554,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[8]),32);
    bufp->chgIData(oldp+555,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[9]),32);
    bufp->chgIData(oldp+556,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[10]),32);
    bufp->chgIData(oldp+557,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[11]),32);
    bufp->chgIData(oldp+558,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[12]),32);
    bufp->chgIData(oldp+559,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[13]),32);
    bufp->chgIData(oldp+560,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[14]),32);
    bufp->chgIData(oldp+561,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[15]),32);
    bufp->chgIData(oldp+562,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[16]),32);
    bufp->chgIData(oldp+563,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[17]),32);
    bufp->chgIData(oldp+564,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[18]),32);
    bufp->chgIData(oldp+565,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[19]),32);
    bufp->chgIData(oldp+566,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[20]),32);
    bufp->chgIData(oldp+567,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[21]),32);
    bufp->chgIData(oldp+568,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[22]),32);
    bufp->chgIData(oldp+569,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[23]),32);
    bufp->chgIData(oldp+570,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[24]),32);
    bufp->chgIData(oldp+571,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[25]),32);
    bufp->chgIData(oldp+572,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[26]),32);
    bufp->chgIData(oldp+573,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[27]),32);
    bufp->chgIData(oldp+574,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[28]),32);
    bufp->chgIData(oldp+575,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[29]),32);
    bufp->chgIData(oldp+576,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[30]),32);
    bufp->chgIData(oldp+577,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[31]),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
